spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
  
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_dev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: password
  
  redis:
    host: localhost
    port: 6379
    password:
  
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    com.ecommerce: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

app:
  security:
    cors:
      allowed-origins: http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000
  
  mail:
    from: dev@ecommerce.local
    base-url: http://localhost:3000
  
  rate-limit:
    enabled: false

springdoc:
  swagger-ui:
    enabled: true