spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
  
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
  
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

logging:
  level:
    root: WARN
    com.ecommerce: INFO
    org.springframework.security: WARN
  file:
    name: /var/log/ecommerce/app.log

app:
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
  
  rate-limit:
    enabled: true

springdoc:
  swagger-ui:
    enabled: false

management:
  endpoint:
    health:
      show-details: never